global using DotNetEnv;
global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using FluentValidation;
global using FluentValidation.AspNetCore.Http;
// global using Microsoft.AspNetCore.Identity;
// global using Microsoft.AspNetCore.Identity.ApiEndpoints;
// global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;